import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeroPage from "./hero/page";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display : 'swap',
  weight : ['100' , '200' , '300' , '400' , '500' , '600' , '700' , '800' , '900']
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistMono.variable} antialiased`}
      >
      <HeroPage/>
        {children}
      </body>
    </html>
  );
}
