import type { Metadata } from "next";
import { Inter, Ballet } from "next/font/google";
import "./globals.css";
import HeroPage from "./hero/page";
import { Weight } from "lucide-react";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const ballet = Ballet({
  variable: "--font-ballet",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Ballet:opsz@16..72&family=Kapakana:wght@300..400&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className={`${inter.variable} antialiased`}>
        <HeroPage />
        {children}
      </body>
    </html>
  );
}
